### ISSUE TITLE
Not working on live 9.1.2 (pc)

### ISSUE THREAD

**Issue by gonbaum** [hdavid/Launchpad95#26]
Script is not responding with Launchpad S and Live 9.1.2 .
Script name appears on settings but nothing happens when is selected.
Log.txt shows :

11914 ms. RemoteScriptError: warning: Not importing directory 'C:\ProgramData\Ableton\Live 9 Suite\Resources\MIDI Remote Scripts\Launchpad95': missing __init__.py

11914 ms. RemoteScriptError: Traceback (most recent call last):

11914 ms. RemoteScriptError:   File "<string>", line 1, in <module>

11914 ms. RemoteScriptError: ImportError
11914 ms. RemoteScriptError: : 
11914 ms. RemoteScriptError: No module named Launchpad95
11914 ms. RemoteScriptError:

**Comment by hdavid** [comment]
usually in the error message the computer is trying to help you and guiding you towards the actual problem.

1914 ms. RemoteScriptError: warning: Not importing directory 'C:\ProgramData\Ableton\Live 9 Suite\Resources\MIDI Remote Scripts\Launchpad95': missing init.py

is this file present ? if you installed correctly it should be there.
https://github.com/hdavid/Launchpad95/blob/master/__init__.py

did you read the FAQ ?

**Comment by gonbaum** [comment]
Yes, of course i read the faq. Writing to you ist my last resource. The
most bizarre thing is that the file is on place.
I dont know what is going wrong.


2015-08-28 3:26 GMT-03:00 henri <notifications@github.com>:

**Comment by hdavid** [comment]
hello,

i was given the info that changing one line in the code did the trick to get it to work. : 
on this line, https://github.com/hdavid/Launchpad95/blob/master/MainSelectorComponent.py#L55
replace DeprecatedSessionZoomingComponent by SessionZoomingComponent and it should work.
at least according to  Reinier. :) thanks Reinier !

"
On your github there’s an open issue “Not working on live 9.1.2 (pc)”. It seems fix “compatibility fix for live 9.1.3b8” has been rolled-back/refactored-out, because if I change the DeprecatedSessionZoomingComponent back to ZoomingComponent in MainSelectorComponent.py, my Launchpad mini mk2 starts up perfectly and works as intended. I currently have no access to your github, so I cannot change your code, but recovering the commit mentioned above (on 11 june 2014) should solve the problem (and make mr. gonbaum, the author of issue #26 happy again, I think)...
"

**Comment by thomasf** [comment]
For me it's not working on 9.2/osx but I'm not sure I've pulled the last 9.2 commit to  my computer yet and I'm more into learning how to make use of my beginners euro rack system (as everyone else these days) to actually use live for more than straight up recording :)

**Comment by gonbaum** [comment]
Sadly isn't working for me neither. Looking forward maybe for a possible solution. Thanks Henri
