### ISSUE TITLE
it is not poping up in midi controls 

### ISSUE THREAD

**Issue by dettrly** [hdavid/Launchpad95#68]
![image](https://user-images.githubusercontent.com/117297268/199533905-aa927a8b-f1e9-4560-aaf0-3fd23b80c184.png)
THERE

**Comment by hdavid** [comment]
it works for 100' of users, please check you put the files correctly as explained in the manual. 
https://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/#toc_3_Setup
https://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/setup-folders.png
check also the FAQ: https://motscousus.com/stuff/2011-07_Novation_Launchpad_Ableton_Live_Scripts/#toc_30_F.A.Q.

if there was an error it would be visible in the Log.txt https://help.ableton.com/hc/en-us/articles/209071629-Where-to-find-Crash-Reports
but i am pretty sure you have put the files at a wrong location as many users got it working.

i double checked, reinstalled the last version of ableton live 10 and it worked just fine.

**Comment by dettrly** [comment]
![image](https://user-images.githubusercontent.com/117297268/199544694-abea5af3-5230-4183-ad99-de822bc3c807.png)


![image](https://user-images.githubusercontent.com/117297268/199544870-2a8bc89f-bb2f-41dc-820a-7669d17d6dde.png)
 can you confirm the images above are in the correct spots.

**Comment by hdavid** [comment]
yes it looks correct. i have no idea. sorry. maybe you changed the path to the user library and live is using another one that the one you show on your screenshot. i have no idea.

as mentioned in the previous comment, check the Log.txt file for an error related to launchpad95. but i am 95% sure the error is because of the file location. 
really, you are not the first user of this script ,)
